### ISSUE TITLE
Error transforming Kubernetes objects

### ISSUE THREAD

**Issue by Arnold1** [kubernetes/kompose#876]
Hi,

i run into some issues with kompose when i run the following command. do you know what is wrong and how to resolve it?
```
kompose convert -f docker-compose.yml
WARN Unsupported links key - ignoring             
WARN Volume mount on the host "./alertmanager/alertmanager.yml" isn't supported - ignoring path on the host 
FATA Error transforming Kubernetes objects: k.UpdateController failed: updateTemplate failed: Unknown restart policy unless-stopped for servicealertmanager
```

docker-compose.yml:
```
version: "2"

services:

  prometheus-server:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus/alert.yml:/etc/prometheus/alert.yml
    links:
      - "alertmanager:alertmanager"

  alertmanager:
    image: prom/alertmanager
    restart: unless-stopped
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/config.yml
    command:
      - '-config.file=/etc/alertmanager/config.yml'
      - '-storage.path=/alertmanager'
      - '-log.level=debug'

  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=password
    links:
      - prometheus-server:prometheus

  go-mux-example:
    image: mux:v1
    ports:
      - 8080:8080
```

**Comment by cdrage** [comment]
Thanks for pointing this out! Looks like `unless-stopped` isn't implemented. We should have a fix out this week :+1:

**Comment by Arnold1** [comment]
what happens if i remove the restart from the yml file?

here is what happens without the restart policy. how can i fix the warnings?
```
$ kompose convert -f docker-compose.yml
WARN Unsupported links key - ignoring             
WARN Volume mount on the host "./alertmanager/alertmanager.yml" isn't supported - ignoring path on the host 
WARN Volume mount on the host "./prometheus/prometheus.yml" isn't supported - ignoring path on the host 
WARN Volume mount on the host "./prometheus/alert.yml" isn't supported - ignoring path on the host 
INFO Kubernetes file "alertmanager-service.yaml" created 
INFO Kubernetes file "go-mux-example-service.yaml" created 
INFO Kubernetes file "grafana-service.yaml" created 
INFO Kubernetes file "prometheus-server-service.yaml" created 
INFO Kubernetes file "alertmanager-deployment.yaml" created 
INFO Kubernetes file "alertmanager-claim0-persistentvolumeclaim.yaml" created 
INFO Kubernetes file "go-mux-example-deployment.yaml" created 
INFO Kubernetes file "grafana-deployment.yaml" created 
INFO Kubernetes file "prometheus-server-deployment.yaml" created 
INFO Kubernetes file "prometheus-server-claim0-persistentvolumeclaim.yaml" created 
INFO Kubernetes file "prometheus-server-claim1-persistentvolumeclaim.yaml" created
```

**Comment by cdrage** [comment]
With regards to the warnings, yes, you're free to ignore them, but due to using host volumes, Kubernetes doesn't support it.

Yup! It should theoretically work (you may have to modify your volumes). Using minikube and doing `kompose up` will bring it up on Kubernetes.

**Comment by Arnold1** [comment]
i installed minicube and can run the sample they have here:
https://github.com/kubernetes/minikube/blob/v0.22.3/README.md

i run into that issue, any why it cannot startup?
```
$ kompose up
WARN Unsupported links key - ignoring             
WARN Volume mount on the host "./alertmanager/alertmanager.yml" isn't supported - ignoring path on the host 
WARN Volume mount on the host "./prometheus/prometheus.yml" isn't supported - ignoring path on the host 
WARN Volume mount on the host "./prometheus/alert.yml" isn't supported - ignoring path on the host 
INFO We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 
 
FATA Error while deploying application: Get https://192.168.99.100:8443/api: dial tcp 192.168.99.100:8443: getsockopt: operation timed out 
```

**Comment by cdrage** [comment]
@Arnold1 for some reason Kompose isn't able to communicate to your Kubernetes cluster.

After you run "minikube start" are you able to access your cluster with kubectl? Ex. `kubectl get pods` ?

**Comment by Arnold1** [comment]
i think i stopped minikube before...

here is what i get now, but only 1 container is running?
```
$ minikube start
Starting local Kubernetes v1.8.0 cluster...
Starting VM...
Getting VM IP address...
Moving files into cluster...
Setting up certs...
Connecting to cluster...
Setting up kubeconfig...
Starting cluster components...
Kubectl is now configured to use the cluster.

$ kompose up
WARN Unsupported links key - ignoring             
WARN Volume mount on the host "./alertmanager/alertmanager.yml" isn't supported - ignoring path on the host 
WARN Volume mount on the host "./prometheus/prometheus.yml" isn't supported - ignoring path on the host 
WARN Volume mount on the host "./prometheus/alert.yml" isn't supported - ignoring path on the host 
INFO We are going to create Kubernetes Deployments, Services and PersistentVolumeClaims for your Dockerized application. If you need different kind of resources, use the 'kompose convert' and 'kubectl create -f' commands instead. 
 
INFO Deploying application in "default" namespace 
INFO Successfully created Service: go-mux-example 
INFO Successfully created Service: grafana        
INFO Successfully created Service: prometheus-server 
INFO Successfully created Pod: alertmanager       
INFO Successfully created PersistentVolumeClaim: alertmanager-claim0 of size 100Mi. If your cluster has dynamic storage provisioning, you don't have to do anything. Otherwise you have to create PersistentVolume to make PVC work 
INFO Successfully created Deployment: go-mux-example 
INFO Successfully created Deployment: grafana     
INFO Successfully created Deployment: prometheus-server 
INFO Successfully created PersistentVolumeClaim: prometheus-server-claim0 of size 100Mi. If your cluster has dynamic storage provisioning, you don't have to do anything. Otherwise you have to create PersistentVolume to make PVC work 
INFO Successfully created PersistentVolumeClaim: prometheus-server-claim1 of size 100Mi. If your cluster has dynamic storage provisioning, you don't have to do anything. Otherwise you have to create PersistentVolume to make PVC work 

Your application has been deployed to Kubernetes. You can run 'kubectl get deployment,svc,pods,pvc' for details.
```

```
$ kubectl get pods
NAME                                 READY     STATUS              RESTARTS   AGE
alertmanager                         0/1       ContainerCreating   0          9s
go-mux-example-7c96ff7bfd-78dz7      0/1       ErrImagePull        0          8s
grafana-85f8b648d8-kqpj9             0/1       ContainerCreating   0          8s
hello-minikube-5bc754d4cd-j7w5t      1/1       Running             1          2h
prometheus-server-6bc89bcb6f-4tvmk   0/1       ContainerCreating   0          8s
```

**Comment by Arnold1** [comment]
@cdrage any idea?

**Comment by cdrage** [comment]
@Arnold1 Unfortunately when it comes down to volumes within Docker Compose / Kompose, it get's fairly tricky.

Mind posting your full docker-compose example (the one you're using now) and we can go from there? Volumes are the worst part of this entire operation, very difficult to get right since some containers (such as prometheus) rely on them to be EXACT.

**Comment by Arnold1** [comment]
@cdrage do you mean all the files?

**Comment by cdrage** [comment]
@Arnold1 just your modified docker-compose.yaml file so I can test it my-side.

I've had a conversion with @kadel  on how we could improve volumes, it's the trickiest part of Kompose unfortunately.

**Comment by Arnold1** [comment]
@cdrage i added all files here: https://github.com/Arnold1/prometheus_kubernetes

**Comment by surajnarwade** [comment]
@Arnold1 , there's no Dockerfile in your repo :(

```
$ ./build_docker.sh 
unable to prepare context: unable to evaluate symlinks in Dockerfile path: lstat /tmp/arnold/prometheus_kubernetes/Dockerfile: no such file or directory
```

**Comment by Arnold1** [comment]
@surajnarwade @cdrage I added the missing dockerfile.

**Comment by Arnold1** [comment]
@cdrage is there a workaround for the meantime?

**Comment by cdrage** [comment]
@Arnold1 Sorry, it's been quite a busy week for us, we're going to try and get around to it this week. It may involve modifying some of the containers since for some reason they like Docker Compose but now when it's on Kubernetes. I'll try your updated repo it soon :+1:

**Comment by Arnold1** [comment]
@cdrage any update?

**Comment by surajnarwade** [comment]
@Arnold1 some of your services has volumes which may contain some file which are necessary for your applcation. Hence, status for your application is `Crashloopbackoff`, Recently I wrote a blog about sharing host directory into minkube (you can check blog [here](http://suraj.pro/post/hostmount-minikube/))

So first do `kompose convert` and generate kubernetes files and then edit those files accordingly with volume details

**Comment by Arnold1** [comment]
@surajnarwade ok, i currently try to find a workaround. how can i make it work?

**Comment by Arnold1** [comment]
@cdrage some time to look into? :)

**Comment by cdrage** [comment]
@Arnold1 Sorry, I haven't found time to look into this yet :( I did have very brief look and as what @surajnarwade said, it's most likely because the containers are trying to retrieve information that's originally suppose to be passed in through volumes.

**Comment by Arnold1** [comment]
will reading and applying @surajnarwade article solve the issue? refering to: http://suraj.pro/post/hostmount-minikube/

**Comment by d-mcd** [comment]
Any update on this? Same issue here when trying to convert from Docker Compose to Kubernetes for containerized applications that use volume mappings out to OS for persistent data.

Thanks

**Comment by cdrage** [comment]
@d-mcd Unfortunately volumes is *very* tricky since it's a completely different concept within Kubernetes. One of the solutions is to create a hostPath volumes which were in the PR and issues here: #109 #734 

We're still investigating and will most likely push a PR out for adding hostPath volumes by next release. It's a hack to get it working (hostPath volumes are only recommended for development), but it's a solution nevertheless.

**Comment by Arnold1** [comment]
hi, just wondering what is the solution now? can i retry and test it? if so how?

**Comment by cdrage** [comment]
@hangyan contributed the hostpath volume, so this is solved! :+1:

**Comment by lmangani** [comment]
@Arnold1 the test [compose file](https://github.com/hangyan/kompose/tree/master/script/test/fixtures/volume-mounts/hostpath) and [command](https://github.com/hangyan/kompose/blob/master/script/test/cmd/tests.sh#L196) in the PR might help

**Comment by vikasgubbi** [comment]
@Arnold1 did you able to run successfully

**Comment by Arnold1** [comment]
have not tested yet, how to test it with latest code?

**Comment by marner2** [comment]
I'm still getting the originally mentioned error: "Unknown restart policy unless-stopped for service" I'm using version 2.20. Did that ever get fixed?

@cdrage [said in this comment from 2.5 years ago:](https://github.com/kubernetes/kompose/issues/876#issuecomment-347223904)

> Thanks for pointing this out! Looks like `unless-stopped` isn't implemented. We should have a fix out this week 👍

**Comment by hangyan** [comment]
@marner2   If this a supported field in version 2, it's a bug. I will look up into it
